dataset:
  path: /home/vincenzo/Documenti/outcome_streaming/Tesi-next_activity/src/dataset/csv/helpdesk2.csv

embedded_model:
  model: sentence-transformers/all-roberta-large-v1

river:
  classifier:
    type: NN
